---
- hosts: localhost

  pre_tasks:
    - name: Setup host name from inventory
      hostname: name=L05

  roles:
    - role: geerlingguy.ntp
    - role: geerlingguy.git
    - role: geerlingguy.apache
      apache_vhosts:
        - {servername: "raccoon1.doe.com", documentroot: "/srv/www/raccoon1.doe.com"}
      apache_remove_default_vhost: true

  tasks:
    - name: Create /srv/www  directory
      file: 
        path: /srv/www
        state: directory
        owner: www-data
        group: www-data
        mode: 0775

    - name: Clone git repository
      git: >
        dest=/srv/www/raccoon1.doe.com
        repo=https://github.com/itraccoons/raccoon1.doe.com.git
        update=no
      become: yes
      become_user: www-data
      notify:
        - restart apache

    - name: Send message to Slack
      slack:
        token: T67ELM0P4/B6F8UFQ5C/Ur8k3wUYQ1rVntbRiB0p0Xm5
        channel: github-itraccoons
        msg: '{{ inventory_hostname }} provisioned with Ansible'
      delegate_to: localhost

  handlers:
    - name: restart apache
      service: name=apache state=restarted


