$docker_stack=<<SCRIPT
    docker swarm init
    docker stack deploy -c /vagrant/docker-compose.yml raccoon1
SCRIPT


VAGRANT_API_VERSION = '2'
Vagrant.configure(VAGRANT_API_VERSION) do |config|
  config.vm.define "node2.docker.vbox" do |_|
    _.vm.box = "ubuntu/trusty64"
    _.vm.network :forwarded_port, guest: 80, host: 8080
    _.vm.provider "virtualbox" do |__|
      __.name = "docker-node2.raccoons.co"
      __.memory = "1024"
      __.cpus = "1"
    end

    _.vm.provision "docker" do |d|
      d.post_install_provision "shell", inline: "sudo curl -L https://github.com/docker/compose/releases/download/1.15.0/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose && sudo chmod +x /usr/local/bin/docker-compose"
      d.build_image "/vagrant/myapp", args: "-t myapp:v0.1"
    end

    _.vm.provision "shell", inline: $docker_stack

  end
end
