# vim: set ft=ruby ts=2 sw=2 et:
# -*- mode: ruby -*-

VAGRANT_API_VERSION = '2'
Vagrant.configure(VAGRANT_API_VERSION) do |config|
  config.vm.define "web" do |_|
    _.vm.box = "centos/7"
    _.vm.network :forwarded_port, guest: 80, host: 8080
    _.vm.provider "virtualbox" do |__|
      __.memory = "1024"
      __.cpus = "1"
    end
  end
end
 