concurrent = 1
check_interval = 0

[[runners]]
  name = "raccoon1"
  url = "https://gitlab.com"
  token = "cb8e4fe11a4393cd5bf6827c8d2090"
  executor = "docker"
  [runners.docker]
    tls_verify = false
    image = "docker:latest"
    privileged = false
    disable_cache = false
    volumes = ["/var/run/docker.sock:/var/run/docker.sock", "/cache"]
    shm_size = 0
  [runners.cache]
