---
#- include: library/presets.yml

- hosts: staging-servers
  gather_facts: "yes"

  tasks:
    - name: Send message to Slack
      slack:
        token: T67ELM0P4/B6F8UFQ5C/Ur8k3wUYQ1rVntbRiB0p0Xm5
        channel: github-itraccoons
        msg: '{{ inventory_hostname }} notify from Ansible'
      delegate_to: localhost
