# vim: set ft=ruby ts=2 sw=2 et:
# -*- mode: ruby -*-

VAGRANT_API_VERSION = '2'
Vagrant.configure(VAGRANT_API_VERSION) do |config|
  config.vm.define "gitlab-runner.vbox" do |_|
    _.vm.box = "ubuntu/trusty64"
    _.vm.network :forwarded_port, guest: 5000, host: 5000
    _.vm.network :forwarded_port, guest: 9000, host: 9000
    _.vm.network :forwarded_port, guest: 8080, host: 8080
    _.vm.provider "virtualbox" do |__|
      __.name = "host.docker.vagrant.vbox"
      __.memory = "1024"
      __.cpus = "1"
    end

    _.vm.provision "docker" do |d|
      d.run "gitlab-runner.container",
        image: "gitlab/gitlab-runner:latest",
        args: "-v '/vagrant/gitlab-runner:/etc/gitlab-runner' -v '/var/run/docker.sock:/var/run/docker.sock'"

      d.run "portainer.container",
        image: "portainer/portainer",
        args: "-p 9000:9000 -v '/var/run/docker.sock:/var/run/docker.sock'"

      d.run "registry-ui.container",
        image: "hyper/docker-registry-web"
        args: "-p 8080:8080 --name registry-web --link registry-srv -e REGISTRY_URL=http://localhost:5000/v2 -e REGISTRY_NAME=localhost:5000"

#      d.run "registry-ui.container",
#        image: "atcol/docker-registry-ui",
#        args: "-p 8080:8080"
    end

  end
end


#after conteiner start run 
#docker exec gitlab-runner.container gitlab-runner register --non-interactive --url https://gitlab.com --registration-token Jsgz5Xht9Pg-6UsyRT5H --executor docker --docker-image docker:latest --docker-volumes /var/run/docker.sock:/var/run/docker.sock --tag-list docker --name raccoon1
