VAGRANT_API_VERSION = '2'
Vagrant.configure(VAGRANT_API_VERSION) do |config|
  config.vm.define "host.docker.vbox" do |_|
    _.vm.box = "ubuntu/trusty64"
    _.vm.network :forwarded_port, guest: 9000, host: 9000
    _.vm.provider "virtualbox" do |__|
      __.name = "host.docker.vagrant.vbox"
      __.memory = "1024"
      __.cpus = "1"
    end

    _.vm.provision "docker" do |d| 
      d.post_install_provision "shell", inline:"docker-compose up"
#      d.pull_images "portainer.container"
    end

  end
end
