VAGRANT_API_VERSION = '2'
Vagrant.configure(VAGRANT_API_VERSION) do |config|
  config.vm.define "node.docker.vbox" do |_|
    _.vm.box = "ubuntu/trusty64"
    _.vm.network :forwarded_port, guest: 9000, host: 9000
    _.vm.network :forwarded_port, guest: 80, host: 8080
    _.vm.network :forwarded_port, guest: 81, host: 8081
    _.vm.network :forwarded_port, guest: 82, host: 8082
    _.vm.network :forwarded_port, guest: 83, host: 8083
    _.vm.provider "virtualbox" do |__|
      __.name = "docker-node1.raccoons.co"
      __.memory = "1024"
      __.cpus = "1"
    end

    _.vm.provision "docker" do |d| 
      d.run "portainer", image: "portainer/portainer", args: "-p 9000:9000 -v '/var/run/docker.sock:/var/run/docker.sock'"

      d.build_image "/vagrant/myapp", args: "-t myapp:v0.1"
      d.run "myapp-nginx", image: "myapp:v0.1", args: "-p 80:80"
      d.run "myapp-nginx2", image: "myapp:v0.1", args: "-p 81:80 -v /vagrant/myapp/www2/doe:/usr/share/nginx/html"
      d.run "myapp-nginx3", image: "nginx:alpine", args: "-p 82:80 --volumes-from myapp-nginx"
    end

    _.vm.provision "shell", inline:"docker create --name datacontainer myapp2:v0.1"

    _.vm.provision "docker" do |d| 
      d.build_image "/vagrant/myapp2", args: "-t myapp2:v0.1"
      d.run "myapp2-nginx4", image: "nginx:alpine", args: "-p 83:80 --volumes-from datacontainer"
    end


  end
end
