# vim: set ft=ruby ts=2 sw=2 et:
# -*- mode: ruby -*-

VAGRANT_API_VERSION = '2'
Vagrant.configure(VAGRANT_API_VERSION) do |config|
  config.vm.define "gitlab-runner.vbox" do |_|
    _.vm.box = "ubuntu/trusty64"
#    _.vm.box = "CentOS/7"
    _.vm.network :forwarded_port, guest: 80, host: 8080
    _.vm.network :forwarded_port, guest: 81, host: 8081
    _.vm.network :forwarded_port, guest: 82, host: 8082
    _.vm.network :forwarded_port, guest: 9000, host: 9000
    _.vm.provider "virtualbox" do |__|
      __.name = "gitlab-runner.docker.vagrant.vbox"
      __.memory = "1024"
      __.cpus = "1"
    end

    _.vm.provision "docker" do |d|
      d.run "gitlab-runner.container",
        image: "gitlab/gitlab-runner:latest",
        args: "-v '/vagrant/gitlab-runner:/etc/gitlab-runner' -v '/var/run/docker.sock:/var/run/docker.sock'"

      d.run "portainer.container",
        image: "portainer/portainer",
        args: "-p 9000:9000 -v '/var/run/docker.sock:/var/run/docker.sock'"
    end

  end
end


#after conteiner start run 
#docker exec gitlab-runner.container gitlab-runner register --non-interactive --url https://gitlab.com --registration-token Jsgz5Xht9Pg-6UsyRT5H --executor docker --docker-image docker:latest --docker-volumes /var/run/docker.sock:/var/run/docker.sock --tag-list docker --name raccoon1
